export interface Cliente {
  id: number;
  nomexx?: string;
  endere?: string;
  bairro?: string;
  cepxxx?: string;
  cpfxxx?: string;
  cnpjxx?: string;
  telres?: string;
  telcom?: string;
  celu1?: string;
  celu2?: string;
  rgxxxx?: string;
  orgem?: string;
  emissa?: string;
  datnas?: Date | string;
  emailx?: string;
  email2?: string;
  paixxx?: string;
  maexxx?: string;
  cidade?: number;
  nomeCidade?: string;
  nomeEstado?: string;
  comple?: string;
  profiss?: string;
  empres?: string;
  rendax?: string;
  bancox?: string;
  agenci?: string;
  contax?: string;
  pix?: string;
  banco1?: string; agencia1?: string; conta1?: string; pix1?: string;
  banco2?: string; agencia2?: string; conta2?: string; pix2?: string;
  refer1?: string; telrefere1?: string;
  refer2?: string; telrefere2?: string;
  obsxxx?: string;
  ocorrencias?: string;
  ativox?: string;
  blocli?: string;
  adm?: string;
  acessoApp?: string;
  senhax?: string;
  limcre?: string;
  classificacao?: number;
  codcla?: string;
  estciv?: string;
  datcad?: Date | string;
  datalt?: Date | string;
  comprovante1?: string;
  comprovante2?: string;
  comprovante3?: string;
  // Permissões de Dashboard (para ADMs)
  verComissoes?: string;
  verValoresLiquidos?: string;
  verInfoFinanceira?: string;
  verTopCompradores?: string;
  verTopVendedores?: string;
  verVencimentos?: string;
}
