-- Adicionar colunas de permissões à tabela Clientes
-- Executar este script no banco de dados para adicionar as colunas necessárias

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Clientes' AND COLUMN_NAME = 'VER_COMISSOES'
)
BEGIN
  ALTER TABLE Clientes ADD VER_COMISSOES CHAR(1) DEFAULT 'S';
  PRINT 'Adicionada coluna VER_COMISSOES';
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Clientes' AND COLUMN_NAME = 'VER_VALORES_LIQUIDOS'
)
BEGIN
  ALTER TABLE Clientes ADD VER_VALORES_LIQUIDOS CHAR(1) DEFAULT 'S';
  PRINT 'Adicionada coluna VER_VALORES_LIQUIDOS';
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Clientes' AND COLUMN_NAME = 'VER_INFO_FINANCEIRA'
)
BEGIN
  ALTER TABLE Clientes ADD VER_INFO_FINANCEIRA CHAR(1) DEFAULT 'S';
  PRINT 'Adicionada coluna VER_INFO_FINANCEIRA';
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Clientes' AND COLUMN_NAME = 'VER_TOP_COMPRADORES'
)
BEGIN
  ALTER TABLE Clientes ADD VER_TOP_COMPRADORES CHAR(1) DEFAULT 'S';
  PRINT 'Adicionada coluna VER_TOP_COMPRADORES';
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Clientes' AND COLUMN_NAME = 'VER_TOP_VENDEDORES'
)
BEGIN
  ALTER TABLE Clientes ADD VER_TOP_VENDEDORES CHAR(1) DEFAULT 'S';
  PRINT 'Adicionada coluna VER_TOP_VENDEDORES';
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Clientes' AND COLUMN_NAME = 'VER_VENCIMENTOS'
)
BEGIN
  ALTER TABLE Clientes ADD VER_VENCIMENTOS CHAR(1) DEFAULT 'S';
  PRINT 'Adicionada coluna VER_VENCIMENTOS';
END
