-- Desconto por fidelidade do cliente em Vendas (aditivo, separado dos descontos existentes)
-- Roda 1x em cada uma das 5 bases: knorr, MacedoLeiloes, LoteRural, G2, MacedoBkp

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'MOVIMENTO_COMPRADOR' AND COLUMN_NAME = 'TIPO_DESCONTO_FIDELIDADE'
)
BEGIN
  ALTER TABLE MOVIMENTO_COMPRADOR ADD TIPO_DESCONTO_FIDELIDADE CHAR(1) NULL;
  PRINT 'Adicionada coluna TIPO_DESCONTO_FIDELIDADE';
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'MOVIMENTO_COMPRADOR' AND COLUMN_NAME = 'DESCONTO_FIDELIDADE'
)
BEGIN
  ALTER TABLE MOVIMENTO_COMPRADOR ADD DESCONTO_FIDELIDADE DECIMAL(18,2) NOT NULL DEFAULT 0;
  PRINT 'Adicionada coluna DESCONTO_FIDELIDADE';
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'MOVIMENTO_COMPRADOR' AND COLUMN_NAME = 'VALOR_DESCONTO_FIDELIDADE'
)
BEGIN
  ALTER TABLE MOVIMENTO_COMPRADOR ADD VALOR_DESCONTO_FIDELIDADE DECIMAL(18,2) NOT NULL DEFAULT 0;
  PRINT 'Adicionada coluna VALOR_DESCONTO_FIDELIDADE';
END
GO

-- VWVendas precisa expor as 3 colunas novas (view não é versionada em .sql,
-- só existe ao vivo no banco).
ALTER VIEW [dbo].[VWVendas]
AS
SELECT M.ID, M.IDLEILAO, M.CODNOT, M.DATLAN, M.DEFESA, M.ST_PARCELA, M.ST_COMISSAO, M.ST_CONTRATO, M.ST_EMBARQUE,
    ML.IDLOTE, L.LOTEXX, L.DESLOT, C.NOMEXX, C.CPFXXX, ML.QTDXXX, ML.VLRPAR, ML.VLRTOT, ML.ID as IDMOVLOTE,
    MC.IDCLI, MC.IDMOVPARC, MC.IDCONDPAGTO, MC.VALORORIGINAL, MC.VALORDESCONTO, MC.VALORPAGAR,
    MC.VALORBASECOMISSAO, MC.COMISSAO, MC.PERCEN, MC.VALORCOMISSAO, MC.VALORBASECOMISSAOVENDEDOR,
    MC.COMISSAOVENDEDOR, MC.VALORCOMISSAOVENDEDOR, MC.FORMA_PAGAMENTO, MC.ID_PROPRIEDADE,
    MC.TIPO_DESCONTO_FIDELIDADE, MC.DESCONTO_FIDELIDADE, MC.VALOR_DESCONTO_FIDELIDADE
FROM dbo.Movimento AS M
    LEFT OUTER JOIN dbo.Movimento_Lote AS ML ON ML.IDMOV = M.ID
    LEFT OUTER JOIN dbo.Lotes AS L ON L.ID = ML.IDLOTE
    LEFT OUTER JOIN dbo.Movimento_Comprador AS MC ON MC.IDMOV = M.ID
    LEFT OUTER JOIN dbo.Clientes AS C ON C.ID = MC.IDCLI
GO
